learning_session/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from .views import SessionListView, SessionCreateView, SessionDetailView, SessionEnterView
from .views import SessionArchiveView, SessionUpdateView, SessionDuplicateView, SessionArchiveListView, SessionListAdminView
from .views import RoleRequestView, RoleRequestAction, RoleRequestListView, GrantRoleView, UserCreateView, UserBulkCreateView, UserBulkListView
from .views import DownloadVadView, DownloadSpeechView, DownloadLogsView, ConsentView, StudentPadView, SessionLeaveView, SessionGroupAnalyticsView, DownloadGroupResponsesView
urlpatterns = [
    path('session/create', login_required(SessionCreateView.as_view()), name='session_create'),
    path('session/edit/<int:pk>/', login_required(SessionUpdateView.as_view()), name='session_edit'),
    path('session/duplicate/<int:pk>/',login_required( SessionDuplicateView.as_view()), name='session_duplicate'),
    path('session/archive/<int:pk>/', login_required(SessionArchiveView.as_view()), name='session_archive'),
    path('session/list', login_required(SessionListView.as_view()), name='session_list'),
    path('session/list/admin', login_required(SessionListAdminView.as_view()), name='session_list_admin'),
    path('session/list/archive', login_required(SessionArchiveListView.as_view()), name='session_list_archive'),
    path('session/show/<int:pk>/', login_required(SessionDetailView.as_view()), name='session_detail'),
    path('session/<int:pk>/group/<int:gk>/', login_required(SessionGroupAnalyticsView.as_view()), name='session_group_detail'),
    path('session/enter', SessionEnterView.as_view(), name='session_enter'),
    path('session/exit',SessionLeaveView.as_view(),name='session_exit'),
    path('session/consent', ConsentView.as_view(), name='session_consent'),
    path('session/student', StudentPadView.as_view(), name='session_student'),
    path('request/<int:pk>/<str:action>/', RoleRequestAction.as_view(), name='role_request_action'),
    path('request/send', RoleRequestView.as_view(), name='request_send'),
    path('request/list', RoleRequestListView.as_view(), name='request_list'),
    path('role/assing', GrantRoleView.as_view(), name='grant_role'),
    path('user/create', UserCreateView.as_view(), name='create_user'),
    path('user/bulk/create', UserBulkCreateView.as_view(), name='create_bulk_user'),
    path('user/bulk/list', UserBulkListView.as_view(), name='list_bulk_user'),
    path('download/vad/<int:pk>', DownloadVadView.as_view(), name='download_vad'),
    path('download/speech/<int:pk>', DownloadSpeechView.as_view(), name='download_speech'),
    path('download/logs/<int:pk>', DownloadLogsView.as_view(), name='download_logs'),
    path('download/responses/<int:pk>', DownloadGroupResponsesView.as_view(), name='download_responses'),

    # REST APIs EndPoints
    path("getStats/<group_padid>", views.getGroupPadStats),
    path("sessions/word_cloud/<session_id>/<group_id>", views.getWordCloud, name='group_word_cloud'),
    path("getRevCount/<ethid>", views.getRevCount, name='getRevisionCount'),
    path("getSpeakingStats/<session_id>", views.getSpeakingStats),
    path("getText/<session_id>/<group_id>",views.getText),
    path("predict/",views.predictCollaboration)

]

taico_cotrack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from .views import change_language
from learning_session.views import UploadVADView, UploadSpeechView, UploadAudioView

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("etherpad_app.urls")),
    path("", include("learning_session.urls")),
    path('about/',TemplateView.as_view(template_name="about.html"), name='about'),
    path('features/',TemplateView.as_view(template_name="features.html"), name='features'),
    path("ckeditor/", include('ckeditor_uploader.urls')),
)

# Adding upload paths without i18
urlpatterns += [path('vad_upload/', UploadVADView.as_view(), name='upload_vad'),
                path('speech_upload/', UploadSpeechView.as_view(), name='upload_speech'),
                path('audio_upload/', UploadAudioView.as_view(), name='upload_audio')
                ]
urlpatterns += [path('i18n/', include("django.conf.urls.i18n"))]
urlpatterns += [ path('change-lang/<lang_code>', change_language, name='change_language')]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += [path('accounts/', include('allauth.urls'))]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import home, logout, change_language, RegisterView, CustomLoginView, ResetPasswordView, ChangePasswordView

urlpatterns = [
    path('',CustomLoginView.as_view(), name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(
             template_name = 'registration/password_reset_confirm.html'), 
             name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    
]

learning_session/models.py
from django.db import models
from django.contrib import admin
from ckeditor_uploader.fields import RichTextUploadingField

# Using custom user model
from django.contrib.auth import get_user_model
User = get_user_model()

import os

class Session(models.Model):
    """Model to store information regarding the learning session
    """
    creator = models.ForeignKey(User, on_delete=models.CASCADE)   #owner of the session
    name = models.CharField(max_length=100)                     #session title
    groups = models.IntegerField()                              #number of groups
    learning_problem = RichTextUploadingField()                 #learning problem
    language = models.CharField(max_length=2)                   #language (to use for speech to text translation)
    created_at = models.DateTimeField(auto_now_add=True)        #created at date and time
    duration = models.DurationField()                           #duration of the activity
    access_allowed = models.BooleanField(default=True)          #whether the access is open to the students or not
    status = models.BooleanField(default=False)                 #status of session, used for archiving the session
    assessment_score = models.IntegerField()                    #to store the teacher's assessment of group's work
    useEtherpad = models.BooleanField(default=False)            #whether to use etherpad or not
    useAVchat = models.BooleanField(default=False)              #whether to use audio video chat or not @todo: for future version
    record_audio = models.BooleanField(default=False)           #whether to record audio during activity
    record_audio_video = models.BooleanField(default=False)     #whether to record audio and video both during the activity
    data_recording_session = models.BooleanField(default=False) #whether the session is just for data collection purposes
    random_group = models.BooleanField(default=False)           #whether the session uses random grouping for collaborative learning
    consent_content = RichTextUploadingField()                  #content of a consent form

    # Tracking configuration variable
    conf_vad = models.BooleanField(default=False)               #whether to perform voice activity detection
    conf_speech = models.BooleanField(default=False)            #whether to perform speech to text conversion
    conf_consent = models.BooleanField(default=False)           #whether to show consent form
    

# Model for storing requests for getting teacher's role
class RoleRequest(models.Model):
    """This model stores request made by users for gaining teacher's role.
    """
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    school =  models.TextField(blank=True)
    class_size = models.IntegerField()
    subject = models.TextField(blank=True)
    decision =  models.BooleanField(default=False)
    pending =  models.BooleanField(default=True)


# Model for storing Etherpad session id
class SessionGroupMap(models.Model):
    """Model to mapping between Etherpad pads and learning session
    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE) 
    eth_groupid = models.CharField(max_length=20)                 


def user_directory_path(instance, filename):
    """Function to create filename to store audio/video file

    Args:
        instance (Session): Session object
        filename (str): name of the file

    Returns:
        filename: complete filename containing session info
    """
    # file will be uploaded to MEDIA_ROOT/session_<id>/group_<id>/user_<id>/<filename>
    return os.path.join(
      "session_%d" % instance.session.id,
      "group_%d" % instance.group, 
      "user_%s" % instance.user.id, 
      filename)


class Audiofl(models.Model):
    """Model to store audio/video file on the server

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)   
    group = models.IntegerField(blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    sequence = models.IntegerField(blank=True)
    description = models.TextField(blank=True)
    fl = models.FileField(upload_to=user_directory_path, blank=True)


class VAD(models.Model):
    """Model to store voice activity detection data

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)
    group = models.IntegerField(blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(blank=True)
    activity = models.BigIntegerField(blank=True)


class Speech(models.Model):
    """Model to store Google Speech-to-Text.  Only available for chrome browser

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)
    group = models.IntegerField(blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(blank=True)
    TextField = models.TextField(blank=True)


class activityLog(models.Model):
    """Model to store activity logs 

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)
    actor = models.ForeignKey(User,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    verb = models.TextField(blank=True)
    object = models.TextField(blank=True)


class Consent(models.Model):
    """Model to store users' consent responses

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    permission = models.BooleanField(default=False)
    given_at = models.DateTimeField(auto_now_add=True)


class observationData(models.Model):
    """Model to store observational data

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    observation = models.TextField(blank=True)


class GroupPin(models.Model):
    """Model to store a secure pin for accessing a group's pad

    """
    session = models.ForeignKey(Session,on_delete=models.CASCADE)
    pin = models.CharField(max_length=6)
    group = models.IntegerField(blank=True)


class DummyAccounts(models.Model):
    """Model to store information about user accounts created by a teachers
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    prefix = models.TextField()
    password_str = models.TextField()
    num_accounts = models.IntegerField()
    status = models.BooleanField(default=False)



admin.site.register(Audiofl)
admin.site.register(Session)
admin.site.register(VAD)
admin.site.register(Speech)
admin.site.register(GroupPin)
admin.site.register(Consent)
admin.site.register(RoleRequest)
admin.site.register(SessionGroupMap)
admin.site.register(DummyAccounts)

learning_session/templates/consent.html
{% extends "base.html" %}
{% load static%}
{% load i18n %}
{% block content %}
    <div class="container shadow bg-light border shadow-lg rounded-3 mt-5">
        <div>
            <p class='display-5 p-3'> {% trans 'Informed consent for participant'%} </p>
        </div>
        <hr/>
        <form method="POST">
            {{ form.media }} 
            {% csrf_token %}
            <div class='px-4 py-2'>
                {{ consent_content | safe}}
            </div>
            <div class="form-check pb-5 d-flex align-items-center">

                    {{form.permission}}
                
                    <label class="p-4 small" for="exampleCheck1">
                      {% blocktrans %} 
                        I confirm that I have read and understood the explanation provided to me.<br/>
                        I have had all my questions answered to my satisfaction, and I voluntarily agree to participate in this study. 
                      {% endblocktrans %}
                    </label><br/>
                  </div>
            <input type="submit" class="btn btn-success mb-4" value="{% trans 'Submit' %}"/>
        </form>
        
    </div>
  <style>
    .order-card {
    color: #fff;
}
table th:first-child{
  border-radius:5px 0 0 5px;
}

table th:last-child{
  border-radius:0 5px 5px 0;
}
.bg-c-blue {
    background: linear-gradient(45deg,#4099ff,#73b4ff);
}

.bg-c-green {
    background: linear-gradient(45deg,#2ed8b6,#59e0c5);
}

.bg-c-yellow {
    background: linear-gradient(45deg,#FFB64D,#ffcb80);
}

.bg-c-pink {
    background: linear-gradient(45deg,#FF5370,#ff869a);
}


.card {
    border-radius: 5px;
    -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
    box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
    border: none;
    margin-bottom: 30px;
    -webkit-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}

.card .card-block {
    padding: 25px;
}

.order-card i {
    font-size: 26px;
}

.f-left {
    float: left;
}

.f-right {
    float: right;
}
  </style>

<script>
  function normalize_array(arr) {
    // Function to normalize writing contribution across groups
    normalize = function(val, max) { 
                  return(val) / (max); 
                };
    max = Math.max.apply(null, arr);
    hold_normed_values=[];
    arr.forEach(function(this_num) {
                  hold_normed_values.push(Math.ceil(5 * normalize(this_num, max)))
                });   
    return(hold_normed_values)
  }


</script>

{% endblock %}  

learning_session/templates/create_bulk_users.html
{% extends "teacher_base.html" %} 
{% load static %} 
{% load i18n %} 
{% block title %} {% trans 'Create Learning Session' %} {% endblock title%} 
{% block content %}

<div class='container'>
<h3 class='fw-light my-3 text-white'>Create users in bulk </h3>
<p class='lead text-white'> Here, you can create users for your lessons.  </p>
<div class="form-content text-white my-1 p-2">
  <div class="border-0 rounded-lg mt-0 mb-3">
    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible  fade show" role="alert">
      <div id="form_errors">
        {% for key, value in form.errors.items %}
        <strong class='lead'>{{key | upper}}</strong> {{ value }}
        {% endfor %}
      </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <div class="">
      <form method="POST">
        {{form.media}} {% csrf_token %}
        <fieldset class="form-group border rounded px-4 py-2 pb-4">
          <legend class="float-none w-auto p-2">User</legend>
          <div class="form-row px-2 py-2">
            <div class="col-lg-4 col-sm-12">
              <div class="form-group">
                <label class="small mb-1"> {{form.prefix.label}} </label>
                {{ form.prefix }}
              </div>
            </div>
          </div>
          <div class="form-row px-2 py-2">
            <div class="col-lg-4 col-sm-12">
              <div class="form-group">
                <label class="small mb-1"> {{form.password.label}} </label>
                {{ form.password }}
              </div>
            </div>
          </div>
          <div class="form-row px-2 py-2">
            <div class="col-lg-4 col-sm-12">
              <div class="form-group">
                <label class="small mb-1"> {{form.how_many.label}} </label>
                {{ form.how_many }}
              </div>
            </div>
          </div>
        </fieldset>
        <div class="form-row mt-4">
          <div class="col-md-12">
            <div class="form-group mt-0 mb-1">
              <button
                name="create"
                class="col-md-12 btn btn-warning"
                id="login"
              >
                {% trans 'Create Users' %}
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
  {% endblock content %}

learning_session/templates/create_user.html
{% extends "teacher_base.html" %} 
{% load static %} 
{% load i18n %} 
{% block title %} {% trans 'Create Learning Session' %} {% endblock title%} 
{% block content %}
<style>
    Django toggle switch class did not work properly.
        That's why style was added in the file for toggle effect.
        */
  label.django-toggle-switch {
    position: relative;
    display: inline-block;
    width: 56px;
    height: 28px;
    padding: 0;
  }
  @media (max-width: 767px) {
    .aligned label.django-toggle-switch {
      width: 56px;
      padding: 0;
    }
  }

  .aligned label.django-toggle-switch + .vCheckboxLabel {
    line-height: 28px;
  }

  label.django-toggle-switch input {
    opacity: 0;
    width: 0;
    height: 0;
  }

  .django-toggle-switch-slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: 0.4s;
    transition: 0.4s;
  }

  .django-toggle-switch-slider:before {
    position: absolute;
    content: "";
    height: 20px;
    width: 20px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: 0.4s;
    transition: 0.4s;
  }

  .django-toggle-switch-primary input:checked + .django-toggle-switch-slider,
  input:checked + .django-toggle-switch-slider {
    background-color: #79aec8;
  }
  .django-toggle-switch-primary
    input:focus
    + .django-toggle-switch-slider
    input:focus
    + .django-toggle-switch-slider {
    box-shadow: 0 0 1px #79aec8;
  }

  .django-toggle-switch-dark-primary
    input:checked
    + .django-toggle-switch-slider,
  input:checked + .django-toggle-switch-slider {
    background-color: #417690;
  }
  .django-toggle-switch-dark-primary
    input:focus
    + .django-toggle-switch-slider
    input:focus
    + .django-toggle-switch-slider {
    box-shadow: 0 0 1px #417690;
  }

  .django-toggle-switch-danger input:checked + .django-toggle-switch-slider,
  input:checked + .django-toggle-switch-slider {
    background-color: #ba2121;
  }
  .django-toggle-switch-danger
    input:focus
    + .django-toggle-switch-slider
    input:focus
    + .django-toggle-switch-slider {
    box-shadow: 0 0 1px #ba2121;
  }

  .django-toggle-switch-warning input:checked + .django-toggle-switch-slider,
  input:checked + .django-toggle-switch-slider {
    background-color: #ff6a00;
  }
  .django-toggle-switch-warning
    input:focus
    + .django-toggle-switch-slider
    input:focus
    + .django-toggle-switch-slider {
    box-shadow: 0 0 1px #ff6a00;
  }

  .django-toggle-switch-success input:checked + .django-toggle-switch-slider,
  input:checked + .django-toggle-switch-slider {
    background-color: #06ad3d;
  }
  .django-toggle-switch-success
    input:focus
    + .django-toggle-switch-slider
    input:focus
    + .django-toggle-switch-slider {
    box-shadow: 0 0 1px #06ad3d;
  }

  input:checked + .django-toggle-switch-slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
  }

  /* Rounded sliders */
  .django-toggle-switch-slider.round {
    border-radius: 28px;
  }

  .django-toggle-switch-slider.round:before {
    border-radius: 50%;
  }

  /* Fix help_text display problem */
  form .aligned .django-toggle-switch + div.help {
    margin-left: 160px;
    padding-left: 10px;
  }

  .django-toggle-switch-success input:checked + .django-toggle-switch-slider,
  input:checked + .django-toggle-switch-slider {
    background-color: #06ad3d;
    boarder-radius: 25px;
  }
  .django-toggle-switch-slider::before {
    position: absolute;
    content: "";
    height: 20px;
    width: 20px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: 0.4s;
    transition: 0.4s;
    border-radius: 10px;
  }
  .django-toggle-switch-slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: 0.4s;
    transition: 0.4s;
    border-radius: 25px;
  }
</style>
<div class='container'>
<h3 class='fw-light my-3 text-white'>Create user </h3>
<p class='lead text-white'> Here, you can create new users with/without teacher's role.  </p>
<div class="form-content text-white my-1 p-2">
  <div class="border-0 rounded-lg mt-0 mb-3">
    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible  fade show" role="alert">
      <div id="form_errors">
        {% for key, value in form.errors.items %}
        <strong class='lead'>{{key | upper}}</strong> {{ value }}
        {% endfor %}
      </div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <div class="">
      <form method="POST">
        {{form.media}} {% csrf_token %}
        <fieldset class="form-group border rounded px-4 py-2 pb-4">
          <legend class="float-none w-auto p-2">User</legend>
          <div class="form-row px-2 py-2">
            <div class="col-lg-4 col-sm-12">
              <div class="form-group">
                <label class="small mb-1"> {{form.name.label}} </label>
                {{ form.name }}
              </div>
            </div>
          </div>
          <div class="form-row px-2 py-2">
            <div class="col-lg-4 col-sm-12">
              <div class="form-group">
                <label class="small mb-1"> {{form.email.label}} </label>
                {{ form.email }}
              </div>
            </div>
          </div>
          <div class="form-row px-2 py-2">
            <div class="col-lg-4 col-sm-12">
              <div class="form-group">
                <label class="small mb-1"> {{form.password.label}} </label>
                {{ form.password }}
              </div>
            </div>
          </div>
          <div class="row form-row p-2">
            <div class="col-lg-4">
              <div class="form-group">
                <label class="small mb-1"> Teacher role </label> <br/>
                {{ form.staff }}
              </div>
            </div>
            
          </div>
        </fieldset>
        <div class="form-row mt-4">
          <div class="col-md-12">
            <div class="form-group mt-0 mb-1">
              <button
                name="create"
                class="col-md-12 btn btn-warning"
                id="login"
              >
                {% trans 'Create User' %}
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
  {% endblock content %}

learning_session/templates/dummy_accounts_list.html
{% extends "teacher_base.html" %}
{% load i18n %}
{% block content %}
<div class='m-3 text-light'>
    <h3 class='fw-light'> Dummy accounts available </h3>
    <p> These are the dummy accounts you have created </p>
</div>

{% if not object_list %}
<div class="my-5 border-1 rounded bg-light p-5 d-flex justify-content-center align-items-center bg-light" style="opacity:.8;">
  <div class="p-3"> 
    You don't have any dummy accounts available.
    
    <div class="mt-3">
      <a href="{% url 'create_bulk_user' %}" type="button" class="btn btn-outline-warning"> Create </a>
    </div>
   </div>
</div>
{% else %}
<div class='m-3 fw-light border rounded p-4 bg-light' style="opacity:.8;">
    <table class="table table-striped mb-3">
        <thead>
            <tr>
                <th scope="col">User prefix</th>
                <th scope="col">Password</th>
                <th scope="col">Number of accounts</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr class=''>
                <td>{{obj.prefix}}</td>
                <td>{{obj.password_str}}</td>
                <td>{{obj.num_accounts}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'create_bulk_user' %}" type="button" class="btn btn-outline-warning"> Create </a>
</div>
{% endif %}
{% endblock %}

learning_session/templates/list_session.html
{% extends "teacher_base.html" %}
{% load i18n %}
{% block title %} {% trans 'Learning Sessions' %} {% endblock title%}
{% block content %}
    {% for session in object_list %}
        <div class="p-2 border-1 rounded-3 m-3 border shadow bg-light" style="opacity:.8;">
            <div class="d-flex justify-content-between mb-0"> 
                <h4 class="px-2"> {{session.name | upper}} </h4>
                <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-cog"> </i> 
                </a>
                <ul class="dropdown-menu bg-white" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'session_edit' session.id %}"><i class="fa fa-edit"></i> {% trans 'Edit' %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'session_duplicate' session.id %}"><i class="fa fa-copy"></i> {% trans 'Duplicate' %}</a></li>
                    
                    <li><a class="dropdown-item" href="{% url 'session_archive' session.id %}"><i class="fa fa-archive"></i> {% trans 'Archive' %}</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'download_responses' session.id %}"><i class="fa fa-file"></i> {% trans 'Download Response' %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'download_vad' session.id %}"><i class="fa fa-download"></i> {% trans 'Download VAD' %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'download_speech' session.id %}"><i class="fa fa-comments"></i> {% trans 'Download Speech' %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'download_logs' session.id %}"><i class="fa fa-file"></i> {% trans 'Download Logs' %}</a></li>
                </ul>    
            </div>
            <p class="px-2 mt-0 small fw-lighter"> {% trans 'Created on' %}: {{session.created_at}} </p>
            <!-- Displaying basic information about the learning session -->
            <div class="px-3 d-flex fs-5">
                <p class="badge bg-white text-dark p-1 mx-2 fw-light">
                    {% trans 'Groups' %}: {{session.groups}} 
                </p>
                <p class="badge bg-white text-dark p-1 mx-2  fw-light">
                    {% trans 'Time' %}: {{session.duration}} 
                </p>
                <p class="badge bg-white text-dark   p-1 mx-2  fw-light">
                    {% trans 'Langauge' %}: {{session.language}} 
                </p>
                

                <br/>
            </div>
            <!-- Displaying group pins -->
            <div class="px-3 mx-2 d-flex fw-light">
                <!-- Accessing all related group pins objects-->
                {% trans 'Access Pins'%}:
                <div id="pins" class='mx-4'>
                    {% for gp_object in session.grouppin_set.all %}
                    {% trans 'Group'%}-{{gp_object.group}}:{{gp_object.pin}}
                    {% endfor %}
                </div>
           </div>

            <!-- Displaying data processing/recording related information -->
            <div class="px-3 mt-3 d-flex">
                {% if session.conf_vad %} 
                    <p class='badge bg-danger text-white  mx-2 fw-light'> 
                        seapking activity detection 
                    </p>
                {% endif %}
                {% if session.conf_speech %} 
                    <p class='badge bg-danger  text-white mx-2 fw-light'> 
                        speech-to-text 
                    </p>
                {% endif %}
            </div>
            <div class="px-3 d-flex">
                {% if session.record_audio %} 
                    <p class='badge bg-danger text-white mx-2 fw-light'> 
                        audio recording 
                    </p>
                {% endif %}
                {% if session.record_audio_video %} 
                    <p class='badge bg-danger text-white mx-2  fw-light'> 
                        video recording 
                    </p>
                {% endif %}
            </div>
            <div class="pb-2 px-2">
                <a href="{% url 'session_detail' session.id %}" class='small btn btn-sm btn-primary fw-light small rounded-pill py-1 px-3'> Check Dashboard </a>
            </div>
        </div>
        <br/>
        <script>
            $(function () {
            $('[data-toggle="popover"]').popover();
            });
            $(function () {
            $('[data-toggle="tooltip"]').tooltip({ trigger: 'hover' });
            });
        </script>
    {% empty %}
      <div class='text-center card p-2 m-3'>
            <div class='card-header'>  
                <h4> {% trans 'No sessions' %} </h4> 
            </div>
            <div class='card-body'>
                <p> 
                    {% trans 'You do not have any sessions.' %}
                    <br/><br/>
                    <a href="{% url 'session_create' %}" class='btn btn-success rounded'>
                        <i class='fa fa-add'></i> {% trans 'Create Session' %} 
                    </a>
                </p>
            </div>
        </div>

    {% endfor%}
        

{% endblock content%}